Number=int(input("Enter your roll number: "))
print(type(Number))
word=input("Enter your name: ")
print(type(word))
cc=input("Enter your course code: ")
print(type(cc))
import os
os.system('cls')
print("Roll no: ",Number)
print("Name: ",word)
print("Course Code: ",cc)